from __future__ import annotations

from typing import Any, Mapping

from .device import DeviceHealth, DeviceRecord


class ServoAdapter:
    name = "servos"

    def discover(
        self, robot_body: Mapping[str, Any], timestamp: float
    ) -> DeviceRecord:
        hardware = robot_body.get("hardware")
        hardware = dict(hardware) if isinstance(hardware, Mapping) else {}
        registry = hardware.get("hardware_registry", {})
        registry = dict(registry) if isinstance(registry, Mapping) else {}
        servos = registry.get("servos", {})
        configured = len(servos) if isinstance(servos, Mapping) else 0
        return DeviceRecord(
            device_id="servos:robot-body",
            name="Robot servos",
            category="servos",
            present=configured > 0,
            available=False,
            ownership=(
                "bx1-web.service"
                if robot_body.get("connected")
                else "unknown"
            ),
            health=DeviceHealth(
                "owned_elsewhere" if configured else "adapter_pending",
                "Configuration only; PWM is never generated by BX1 OS",
            ),
            details={
                "configured_count": configured,
                "device_or_bus": "Robot Body hardware bridge",
                "faults": [],
                "adapter_state": "read_only_proxy",
            },
            last_seen=timestamp if robot_body.get("connected") else None,
            capabilities={"status_proxy": True, "pwm": False, "control": False},
            source="Existing Robot Body configuration",
        )
