\
"""
BX1 GUI Controller
==================

This module is the bridge between Master_Main.py and the PySide6 GUI.

Design rule:
    GUI -> GUIController -> Master_Main.py
    Master_Main.py -> GUIController -> GUI

The GUI controller contains no robot control, LLM, STT, TTS or audio logic.
It only transfers application state, events and user requests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, Optional
import threading
import time
import uuid

from PySide6.QtCore import QObject, Signal, Slot


@dataclass
class GUICommand:
    """A command generated by the GUI and intended for Master_Main.py."""
    name: str
    data: Dict[str, Any]


class GUIController(QObject):
    """
    Thread-safe bridge between Master_Main.py and the GUI.

    Master_Main.py can call the public publish_* methods from worker threads.
    Qt signals safely marshal the update back to the GUI thread.

    The GUI sends commands back through `command_requested`.
    Master_Main.py should connect a handler to that signal or register
    a callback with set_command_handler().
    """

    mode_changed = Signal(str)
    connection_changed = Signal(bool, str)

    user_message_received = Signal(str, str)       # message_id, text
    background_message_received = Signal(str, str) # message_id, text
    leo_message_received = Signal(str, str)        # message_id, text

    event_received = Signal(dict)
    telemetry_received = Signal(dict)
    reply_metrics_received = Signal(str, dict)     # message_id, metrics

    video_frame_received = Signal(bytes, dict)       # JPEG, stream metadata
    vision_result_received = Signal(bytes, dict)     # annotated JPEG, YOLO data
    vision_status_received = Signal(dict)

    head_state_received = Signal(dict)
    head_status_received = Signal(dict)

    robot_api_telemetry_received = Signal(dict)
    robot_api_status_received = Signal(dict)

    tts_settings_received = Signal(dict)

    command_requested = Signal(object)              # GUICommand
    clear_requested = Signal()

    def __init__(self) -> None:
        super().__init__()

        self._mode = "LOCAL"
        self._robot_connected = False
        self._robot_name = "LEO-01"

        self._command_handler: Optional[Callable[[GUICommand], None]] = None
        self._handler_lock = threading.RLock()

        self.command_requested.connect(self._dispatch_command)

    # ------------------------------------------------------------------
    # GUI -> MASTER_MAIN
    # ------------------------------------------------------------------

    def set_command_handler(
        self,
        handler: Optional[Callable[[GUICommand], None]],
    ) -> None:
        """
        Register the function in Master_Main.py that should receive GUI commands.

        Example:
            gui_controller.set_command_handler(handle_gui_command)
        """
        with self._handler_lock:
            self._command_handler = handler

    @Slot(object)
    def _dispatch_command(self, command: GUICommand) -> None:
        with self._handler_lock:
            handler = self._command_handler

        if handler is not None:
            handler(command)

    def request_user_message(self, text: str) -> None:
        """
        Called by the GUI when the user types a message.

        Master_Main.py decides what happens to it in LOCAL or ROBOT mode.
        """
        text = str(text or "").strip()
        if not text:
            return

        self.command_requested.emit(
            GUICommand(
                name="user_message",
                data={"text": text},
            )
        )

    def request_action(self, action: str, **data: Any) -> None:
        """
        Generic GUI command helper.

        Example:
            controller.request_action("export_debug")
        """
        self.command_requested.emit(
            GUICommand(
                name=str(action),
                data=dict(data),
            )
        )

    # ------------------------------------------------------------------
    # MASTER_MAIN -> GUI
    # ------------------------------------------------------------------

    def set_mode(self, mode: str) -> None:
        mode = str(mode or "LOCAL").upper()
        self._mode = mode
        self.mode_changed.emit(mode)

    def set_robot_connection(
        self,
        connected: bool,
        robot_name: str = "LEO-01",
    ) -> None:
        self._robot_connected = bool(connected)
        self._robot_name = str(robot_name or "LEO-01")

        self.connection_changed.emit(
            self._robot_connected,
            self._robot_name,
        )

    def publish_user_message(
        self,
        text: str,
        message_id: Optional[str] = None,
    ) -> str:
        if message_id is None:
            message_id = self.new_message_id()

        self.user_message_received.emit(
            message_id,
            str(text),
        )

        return message_id

    def publish_background_message(
        self,
        text: str,
        message_id: Optional[str] = None,
    ) -> str:
        """
        Publish speech heard by STT that was not addressed to LEO.

        Background speech is a diagnostic GUI item only. Master_Main_GUI.py
        decides this classification before publishing it and does not send
        these messages to the LLM.
        """
        if message_id is None:
            message_id = self.new_message_id()

        self.background_message_received.emit(
            message_id,
            str(text),
        )

        return message_id

    def publish_leo_message(
        self,
        text: str,
        message_id: Optional[str] = None,
    ) -> str:
        if message_id is None:
            message_id = self.new_message_id()

        self.leo_message_received.emit(
            message_id,
            str(text),
        )

        return message_id

    def publish_event(
        self,
        event_name: str,
        *,
        source: str = "MASTER",
        message_id: Optional[str] = None,
        data: Optional[Dict[str, Any]] = None,
        timestamp: Optional[float] = None,
    ) -> Dict[str, Any]:
        """
        Publish a system event to the GUI.

        These events are intended to become the basis of the reply inspector
        and future offline debug export.
        """
        event = {
            "timestamp": float(timestamp if timestamp is not None else time.time()),
            "source": str(source),
            "event": str(event_name),
            "message_id": message_id,
            "data": dict(data or {}),
        }

        self.event_received.emit(event)
        return event

    def publish_telemetry(self, telemetry: Dict[str, Any]) -> None:
        """
        Publish a telemetry snapshot.

        The dictionary is intentionally generic so existing BX1 modules
        do not have to be restructured.
        """
        packet = dict(telemetry or {})

        if "timestamp" not in packet:
            packet["timestamp"] = time.time()

        self.telemetry_received.emit(packet)

    def publish_reply_metrics(
        self,
        message_id: str,
        metrics: Dict[str, Any],
    ) -> None:
        """
        Publish timing/system information for a generated reply.

        Example keys:
            stt_ms
            llm_ms
            tts_ms
            playback_ms
            total_response_ms
            total_interaction_ms
            model
            robot_state
        """
        self.reply_metrics_received.emit(
            str(message_id),
            dict(metrics or {}),
        )

    def publish_video_frame(
        self,
        jpeg_bytes: bytes,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.video_frame_received.emit(
            bytes(jpeg_bytes),
            dict(metadata or {}),
        )

    def publish_vision_result(
        self,
        annotated_jpeg: bytes,
        result: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.vision_result_received.emit(
            bytes(annotated_jpeg),
            dict(result or {}),
        )

    def publish_vision_status(
        self,
        status: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.vision_status_received.emit(
            dict(status or {})
        )

    def publish_head_state(
        self,
        state: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.head_state_received.emit(
            dict(state or {})
        )

    def publish_head_status(
        self,
        status: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.head_status_received.emit(
            dict(status or {})
        )

    def publish_robot_api_telemetry(
        self,
        packet: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.robot_api_telemetry_received.emit(
            dict(packet or {})
        )

    def publish_robot_api_status(
        self,
        status: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.robot_api_status_received.emit(
            dict(status or {})
        )

    def publish_tts_settings(
        self,
        settings: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Publish the active Qwen voice/TTS settings to the GUI."""
        self.tts_settings_received.emit(
            dict(settings or {})
        )

    def clear_gui(self) -> None:
        self.clear_requested.emit()

    # ------------------------------------------------------------------
    # HELPERS
    # ------------------------------------------------------------------

    @staticmethod
    def new_message_id() -> str:
        return "msg_" + uuid.uuid4().hex[:10]

    @property
    def mode(self) -> str:
        return self._mode

    @property
    def robot_connected(self) -> bool:
        return self._robot_connected

    @property
    def robot_name(self) -> str:
        return self._robot_name
